/* Medalhas evolutivas: regras puras, sem persistência, rede, XP ou dados particulares. */
(function (raiz) {
  'use strict';
  function runtime() {
    'use strict';
    var contagem=[1,5,10,20,30],circuitos=[1,3,5,10,20],dias=[1,5,10,25,50,100,200,500,1000];
    var catalogo=[];
    function def(id,n,grupo,icone,metrica,metas,unidade,criterio,filtro){grupo={'Constância':'treino','Musculação':'treino','Circuitos':'circuito','Corrida':'corrida','Bike':'bike','Caminhada':'caminhada','Nutrição':'nutricao','Hábitos':'habitos','Acompanhamento':'outros','HYROX':'hyrox'}[grupo]||grupo;var d={id:id,n:n,grupo:grupo,icone:icone,metrica:metrica,metas:metas.slice(),unidade:unidade,criterio:criterio};if(filtro)d.filtro=filtro;catalogo.push(d);}
    def('treinos-dias','Sua jornada de treinos','Constância','medalha','diasTreino',dias,'dias de treino','Dias marcados como treinados, sem duplicar atividades do mesmo dia.');
    def('treinos-semanas','Semanas na meta','Constância','trofeu','semanasMeta',[1,2,4,8,12,24,52,104],'semanas','Semanas com a meta atual de dias de treino alcançada.');
    def('forca-registros','Força acompanhada','Musculação','halter','diasCarga',[1,5,10,25,50,100,200],'dias com carga','Dias com ao menos uma carga confirmada.');
    def('circuitos-registros','Jornada nos circuitos','Circuitos','raio','circuitos',circuitos,'registros','Resultados de circuitos no histórico disponível, incluindo adaptados.');
    ['amrap','fortime','emom','tabata'].forEach(function(t){def('circuitos-'+t,{amrap:'AMRAP',fortime:'For Time',emom:'EMOM',tabata:'Tabata'}[t]+' em ação','Circuitos','raio','circuitosTipo',circuitos,'registros','Resultados deste formato no histórico disponível.',{tipo:t});});
    def('corrida-registros','Passos de corredor','Corrida','corrida','corridas',contagem,'corridas','Corridas válidas do histórico disponível (até 30 atividades).');
    def('corrida-distancia','Sua maior corrida','Corrida','bandeira','corridaKmMax',[1,3,5,10,15,21.1,30,42.2],'km em uma corrida','Maior distância registrada no histórico disponível.');
    def('corrida-km','Quilômetros corridos','Corrida','mapa','corridaKmHistorico',[5,10,25,50,75,100,150,200],'km no histórico','Soma das corridas no histórico disponível; não é um total vitalício.');
    def('bike-registros','Jornada no pedal','Bike','bike','pedais',contagem,'pedais','Pedais válidos do histórico disponível (até 30 atividades).');
    def('bike-distancia','Seu maior pedal','Bike','bandeira','bikeKmMax',[5,10,20,30,50,75,100],'km em um pedal','Maior distância de bike no histórico disponível.');
    def('caminhada-registros','Caminhar faz parte','Caminhada','pegadas','caminhadas',contagem,'caminhadas','Caminhadas válidas no histórico disponível (até 30 atividades).');
    def('caminhada-distancia','Seu caminho','Caminhada','mapa','caminhadaKmMax',[1,2,3,5,7,10],'km em uma caminhada','Maior caminhada no histórico disponível.');
    def('nutri-dias','Constância alimentar','Nutrição','maca','nutriDias',[1,3,7,14,30,60,100,200],'dias de diário','Dias com registros alimentares confirmados. Não avalia restrição calórica.');
    def('nutri-registros','Diário em dia','Nutrição','prato','nutriRegistros',[1,5,10,25,50,100,200,500],'registros','Refeições confirmadas; editar o mesmo registro não conta novamente.');
    def('nutri-semana','Sua semana alimentar','Nutrição','calendario','nutriSemanaDias',[1,3,5,7],'dias em 7','Dias registrados nos últimos sete dias; a janela acompanha sua rotina.');
    [['agua','Água em dia','gota','habitosAgua'],['alimentacao','Alimentação acompanhada','maca','habitosAlimentacao'],['sono','Sono acompanhado','lua','habitosSono'],['cardio','Movimento no dia','ativ','habitosCardio']].forEach(function(a){def('habito-'+a[0],a[1],'Hábitos',a[2],a[3],[1,3,7,14,30,60,100,200],'dias marcados','Dias em que você confirmou este hábito.');});
    def('habitos-equilibrio','Rotina acompanhada','Hábitos','calendario','diasTresHabitos',[1,3,7,14,30,60,100],'dias com 3 hábitos','Dias com pelo menos três hábitos confirmados.');
    def('acompanhamento-peso','Evolução registrada','Acompanhamento','grafico','pesagens',[1,3,5,10,20,30,50],'pesagens','Datas com peso registrado, sem premiar redução de peso.');
    def('acompanhamento-checkins','Conversa em dia','Acompanhamento','check','checkins',[1,3,5,10,20,30,50],'respostas','Check-ins e questionários respondidos.');
    ['HYROX','HYROX Single','HYROX Doubles','HYROX Relay'].forEach(function(nome,i){def('hyrox-registros-'+i,'Registros de '+nome,'HYROX','raio','circuitosNome',circuitos,'registros','Circuito salvo com este nome exato. Não certifica prova oficial nem execução de estações.',{nome:nome});});
    var metricasPermitidas=['diasTreino','semanasMeta','diasCarga','circuitos','circuitosNome','circuitosTipo','corridas','corridaKmMax','corridaKmHistorico','pedais','bikeKmMax','bikeKmHistorico','caminhadas','caminhadaKmMax','caminhadaKmHistorico','nutriDias','nutriRegistros','nutriSemanaDias','habitosAgua','habitosAlimentacao','habitosSono','habitosCardio','diasTresHabitos','pesagens','checkins'];
    var limitadas=['circuitos','circuitosNome','circuitosTipo','corridas','corridaKmMax','corridaKmHistorico','pedais','bikeKmMax','bikeKmHistorico','caminhadas','caminhadaKmMax','caminhadaKmHistorico','nutriSemanaDias'];
    function copia(x){return JSON.parse(JSON.stringify(x));}
    function nomeChave(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/\s+/g,' ');}
    function texto(s,max){return typeof s==='string'?s.trim().slice(0,max):'';}
    function metasLimpas(v){if(!Array.isArray(v)||!v.length||v.length>20)throw new Error('Defina entre 1 e 20 metas crescentes.');var ant=0;return v.map(function(n){if(typeof n!=='number'||!Number.isFinite(n)||n<=ant||n>1000000)throw new Error('As metas devem ser números positivos em ordem crescente.');ant=n;return n;});}
    function definicao(d){if(!d||typeof d!=='object'||!/^[-a-zA-Z0-9_]{1,100}$/.test(d.id||'')||metricasPermitidas.indexOf(d.metrica)<0)throw new Error('Medalha ou critério inválido.');var n=texto(d.n||d.nome,80);if(!n)throw new Error('Dê um nome à medalha.');var out={id:d.id,n:n,grupo:texto(d.grupo,40)||'Outras',icone:texto(d.icone,40)||'medalha',metrica:d.metrica,metas:metasLimpas(d.metas),unidade:texto(d.unidade,60)||'registros'};if(d.fonte)out.fonte=texto(d.fonte,300);if(d.criterio)out.criterio=texto(d.criterio,300);if(d.metrica==='circuitosNome'){var nome=texto(d.filtro&&d.filtro.nome,100);if(!nome)throw new Error('Defina o nome exato do circuito.');out.filtro={nome:nome};}if(d.metrica==='circuitosTipo'){var tipo=d.filtro&&d.filtro.tipo;if(['amrap','fortime','emom','tabata'].indexOf(tipo)<0)throw new Error('Formato de circuito inválido.');out.filtro={tipo:tipo};}return out;}
    function normaliza(selecoes){if(selecoes==null)return [];if(!Array.isArray(selecoes)||selecoes.length>500)throw new Error('Selecione até 500 medalhas.');var vistas={},out=[];selecoes.forEach(function(s){if(typeof s==='string')s={id:s};if(!s||vistas[s.id])return;var base=catalogo.find(function(d){return d.id===s.id;});if(!base)throw new Error('Medalha não encontrada no catálogo.');var item=definicao(Object.assign({},base,{n:s.nome||s.n||base.n,metas:s.metas||base.metas}));vistas[item.id]=true;out.push({id:item.id,nome:item.n,metas:item.metas});});return out;}
    var padrao=['treinos-dias','circuitos-registros','corrida-registros','corrida-distancia','nutri-dias','habito-agua'];
    function pacote(selecoes){return normaliza(selecoes==null?padrao:selecoes).map(function(s){var base=catalogo.find(function(d){return d.id===s.id;});return definicao(Object.assign({},base,{n:s.nome,metas:s.metas}));});}
    function dataOk(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))return false;var d=new Date(s+'T12:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===s;}
    function numero(n){return typeof n==='number'&&Number.isFinite(n)&&n>0?n:0;}
    function objeto(v){return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}
    function metricas(s){s=s||{};var hoje=dataOk(s.hoje)?s.hoje:new Date().toISOString().slice(0,10),m={},porNome=Object.create(null),porTipo=Object.create(null),semanas={};metricasPermitidas.forEach(function(k){m[k]=0;});function dia(d){return dataOk(d)&&d<=hoje;}var f=objeto(s.feitos);Object.keys(f).forEach(function(d){if(!dia(d)||!f[d])return;m.diasTreino++;var dt=new Date(d+'T12:00:00Z');dt.setUTCDate(dt.getUTCDate()-((dt.getUTCDay()+6)%7));var w=dt.toISOString().slice(0,10);semanas[w]=(semanas[w]||0)+1;});var meta=Number.isFinite(s.metaSem)&&s.metaSem>=1&&s.metaSem<=7?s.metaSem:3;m.semanasMeta=Object.keys(semanas).filter(function(w){return semanas[w]>=meta;}).length;
      var cargasDias={};Object.keys(objeto(s.cargas)).forEach(function(ex){var ls=s.cargas[ex];if(!Array.isArray(ls))return;ls.forEach(function(r){if(r&&dia(r.d)&&r.kg!=null&&isFinite(+r.kg)&&+r.kg>=0&&(r.g!==2||r.feito===true))cargasDias[r.d]=1;});});m.diasCarga=Object.keys(cargasDias).length;
      Object.keys(objeto(s.wodres)).forEach(function(id){var ls=s.wodres[id];if(!Array.isArray(ls))return;ls.forEach(function(r){if(!r||r.nf===1||r.nf===true||!dia(r.d)||typeof r.n!=='string'||!r.n.trim()||typeof r.r!=='string'||!r.r.trim())return;m.circuitos++;var k=nomeChave(r.n);porNome[k]=(porNome[k]||0)+1;if(['amrap','fortime','emom','tabata'].indexOf(r.tp)>=0)porTipo[r.tp]=(porTipo[r.tp]||0)+1;});});m.wodPorNome=porNome;m.wodPorTipo=porTipo;
      (Array.isArray(s.cardio)?s.cardio:[]).forEach(function(r){if(!r||!dia(r.d)||numero(r.s)<5||['corrida','bike','caminhada'].indexOf(r.m)<0)return;var pref={corrida:'corrida',bike:'bike',caminhada:'caminhada'}[r.m],count={corrida:'corridas',bike:'pedais',caminhada:'caminhadas'}[r.m];m[count]++;if(numero(r.k)){m[pref+'KmMax']=Math.max(m[pref+'KmMax'],r.k);m[pref+'KmHistorico']+=r.k;}});
      Object.keys(objeto(s.habitos)).forEach(function(d){if(!dia(d))return;var h=s.habitos[d]&&typeof s.habitos[d]==='object'?s.habitos[d]:{},n=0;['habitosAgua','habitosAlimentacao','habitosSono','habitosCardio'].forEach(function(k,i){if(h[i]===true||h[i]===1){m[k]++;n++;}});if(n>=3)m.diasTresHabitos++;});m.pesagens=Object.keys(objeto(s.peso)).filter(function(d){return dia(d)&&numero(s.peso[d]);}).length;m.checkins=Object.keys(objeto(s.qa)).filter(function(d){var v=s.qa[d],chave=d.split('|').pop();return !!v&&dia(typeof v==='string'?v:v&&v.d||v&&v.em&&String(v.em).slice(0,10)||chave);}).length+Object.keys(objeto(s.checkins)).filter(function(d){return !!s.checkins[d]&&dia(d);}).length;
      var nutr=objeto(s.nutricao),nd={};if(nutr.registros&&typeof nutr.registros==='object'&&!Array.isArray(nutr.registros)){Object.keys(nutr.registros).forEach(function(id){var r=nutr.registros[id];if(r&&!r.apagado&&dia(r.d)){m.nutriRegistros++;nd[r.d]=1;}});m.nutriDias=Object.keys(nd).length;var ini=new Date(hoje+'T12:00:00Z');ini.setUTCDate(ini.getUTCDate()-6);var desde=ini.toISOString().slice(0,10);m.nutriSemanaDias=Object.keys(nd).filter(function(d){return d>=desde;}).length;}return m;
    }
    function progresso(def,m){var d=definicao(def);m=m||{};var valor=d.metrica==='circuitosNome'?numero((m.wodPorNome||{})[nomeChave(d.filtro.nome)]):d.metrica==='circuitosTipo'?numero((m.wodPorTipo||{})[d.filtro.tipo]):numero(m[d.metrica]);var metas=d.metas.slice(),limitado=limitadas.indexOf(d.metrica)>=0,nivel=0;while(nivel<metas.length&&valor+1e-9>=metas[nivel])nivel++;var atual=nivel?metas[nivel-1]:0,proxima=metas[nivel]||null;if(!proxima&&!limitado){var passo=d.id==='treinos-dias'?500:(metas.length>1?metas[metas.length-1]-metas[metas.length-2]:metas[0]);var extras=Math.floor((valor-atual)/passo);nivel+=extras;atual+=extras*passo;proxima=atual+passo;}var restante=proxima==null?0:Math.max(0,proxima-valor),percentual=proxima==null?100:Math.round(100*Math.max(0,Math.min(1,(valor-atual)/(proxima-atual))));return {valor:valor,nivel:nivel,atual:atual,proxima:proxima,restante:restante,percentual:percentual,metas:metas,limiteHistorico:limitado};}
    return {catalogo:catalogo,padrao:padrao,normaliza:normaliza,pacote:pacote,definicao:definicao,progresso:progresso,metricas:metricas,nomeChave:nomeChave};
  }
  var api=runtime();api.runtime=runtime;raiz.MT_MEDALHAS=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof self!=='undefined'?self:globalThis);
